def russian_ipa_mapping
	dict = {}

	dict["Б"] = dict["б"] = "b"
	dict["В"] = dict["в"] = "v"
	dict["Г"] = dict["г"] = "ɡ"
	dict["Д"] = dict["д"] = "d"
	dict["Ж"] = dict["ж"] = "ʐ"
	dict["З"] = dict["з"] = "z"
	dict["К"] = dict["к"] = "k"
	dict["Л"] = dict["л"] = "l"
	dict["М"] = dict["м"] = "m"
	dict["Н"] = dict["н"] = "n"
	dict["П"] = dict["п"] = "p"
	dict["Р"] = dict["р"] = "r"
	dict["С"] = dict["с"] = "s"
	dict["Т"] = dict["т"] = "t"
	dict["Ф"] = dict["ф"] = "f"
	dict["Х"] = dict["х"] = "x"
	dict["Ц"] = dict["ц"] = "t͡s"
	dict["Ч"] = dict["ч"] = "tʃʲ"
	dict["Ш"] = dict["ш"] = "ʂ"
	dict["Щ"] = dict["щ"] = "ɕː"
	dict["Й"] = dict["й"] = "j"
	# dict["Ъ"] = dict["ъ"] = "" #is meant to be a "
	dict["А"] = dict["а"] = "a"
	dict["И"] = dict["и"] = "i"
	dict["О"] = dict["о"] = "o"
	dict["У"] = dict["ў"] = "u"
	dict["У"] = dict["у"] = "ʉ"
	dict["Ы"] = dict["ы"] = "ɨ"
	dict["Ь"] = dict["ь"] = "ʲ"
	dict["Э"] = dict["э"] = "ɛ"

	dict["вь"] = dict["ВЬ"] = "fʲ"
	dict["ль"] = dict["ЛЬ"] = "lʲ"
	dict["нь"] = dict["НЬ"] = "nʲ"
	dict["бь"] = dict["БЬ"] = "pʲ"
	dict["рь"] = dict["РЬ"] = "rʲ"
	dict["сь"] = dict["СЬ"] = "zʲ"
	dict["жч"] = dict["ЖЧ"] = "ɕː"
	dict["зж"] = dict["ЗЖ"] = "ʑː"
	dict["жж"] = dict["ЖЖ"] = "ʑː"

	dict["ЖЕ"] = dict["Же"] = dict["жЕ"] = dict["же"] = dict["ШЕ"] = dict["Ше"] = dict["шЕ"] = dict["ше"] = dict["ЦЕ"] = dict["Це"] = dict["цЕ"] = dict["це"] = "ɛ"
	dict["ЧЕ"] = dict["Че"] = dict["чЕ"] = dict["че"] = dict["ЩЕ"] = dict["Ще"] = dict["щЕ"] = dict["ще"] = "e"
	dict["Е"] = dict["е"] = "ʲe"
	dict["ЬЕ"] = dict["Ье"] = dict["ьЕ"] = dict["ье"] = dict["ЪЕ"] = dict["Ъе"] = dict["ъЕ"] = dict["ъе"] = dict["^Е"] = dict["^е"] = "je"

	dict["ЖЁ"] = dict["Жё"] = dict["жЁ"] = dict["жё"] = dict["ШЁ"] = dict["Шё"] = dict["шЁ"] = dict["шё"] = dict["ЦЁ"] = dict["Цё"] = dict["цЁ"] = dict["цё"] = "o"
	dict["ЧЁ"] = dict["Чё"] = dict["чЁ"] = dict["чё"] = dict["ЩЁ"] = dict["Щё"] = dict["щЁ"] = dict["щё"] = "o"
	dict["Ё"] = dict["ё"] = "ʲo"
	dict["ЬЁ"] = dict["Ьё"] = dict["ьЁ"] = dict["ьё"] = dict["ЪЁ"] = dict["Ъё"] = dict["ъЁ"] = dict["ъё"] = dict["^Ё"] = dict["^ё"] = "jo"
	
	dict["ЖЮ"] = dict["Жю"] = dict["жЮ"] = dict["жю"] = dict["ШЮ"] = dict["Шю"] = dict["шЮ"] = dict["шю"] = dict["ЦЮ"] = dict["Цю"] = dict["цЮ"] = dict["цю"] = "u"
	dict["ЧЮ"] = dict["Чю"] = dict["чЮ"] = dict["чю"] = dict["ЩЮ"] = dict["Щю"] = dict["щЮ"] = dict["щю"] = "u"
	dict["Ю"] = dict["ю"] = "ʲu"
	dict["ЬЮ"] = dict["Ью"] = dict["ьЮ"] = dict["ью"] = dict["ЪЮ"] = dict["Ъю"] = dict["ъЮ"] = dict["ъю"] = dict["^Ю"] = dict["^ю"] = "ʉ"
	
	dict["ЖЯ"] = dict["Жя"] = dict["жЯ"] = dict["жя"] = dict["ШЯ"] = dict["Шя"] = dict["шЯ"] = dict["шя"] = dict["ЦЯ"] = dict["Ця"] = dict["цЯ"] = dict["ця"] = "a"
	dict["ЧЯ"] = dict["Чя"] = dict["чЯ"] = dict["чя"] = dict["ЩЯ"] = dict["Щя"] = dict["щЯ"] = dict["щя"] = "a"
	dict["Я"] = dict["я"] = "ʲa"
	dict["ЬЯ"] = dict["Ья"] = dict["ьЯ"] = dict["ья"] = dict["ЪЯ"] = dict["Ъя"] = dict["ъЯ"] = dict["ъя"] = dict["^Я"] = dict["^я"] = "ja"

	dict
end